Added a property called "rotate"
wvengen/d3-wordcloud pull request #10
Opened 2017-10-21 00:02 UTC by diotto

I've created a property called rotate and changed example to use it. In example i changed the behavior of words to stay only in 0 ou 90 degrees.

2017-11-13 16:52 UTC, ScottChapman commented
Would love this, please merge?

2017-12-14 11:59 UTC, diotto commented
@ScottChapman as my pull request was not accepted, you can see my modified version at https://github.com/diotto/d3-wordcloud

2017-12-22 09:01 UTC, wvengen requested changes
Thanks for the contribution. There are some small comments, would love to integrate this when ready!

2017-12-22 09:01 UTC, wvengen commented on d3.wordcloud.js
> +      return wordcloud
missing semicolon

2017-12-22 09:01 UTC, wvengen commented on d3.wordcloud.js
> +        .rotate(rotate)
Why not put the default function here, and allow `rotate` to be null? Avoids having the function twice.

2018-10-23 02:16 UTC, closed without merging